# Generated by Django 3.0.4 on 2020-03-15 12:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_date', models.DateTimeField(auto_created=True, auto_now=True, verbose_name='Last Update Date')),
                ('create_date', models.DateTimeField(auto_created=True, auto_now_add=True, verbose_name='Record Create Date')),
                ('full_path', models.URLField(verbose_name='Image Full Path')),
                ('short_path', models.URLField(verbose_name='Image Short Path')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
